/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Doctor;

import Business.BloodBank.BloodBank;
import Business.Hospital.Doctor;
import Business.Request.Request;
import Business.Request.RequestDirectory;
import Business.System.ConfigureASystem;
import Business.System.Ecosystem;
import Business.User.User;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kalyanijohare
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private Ecosystem ecosystem;
    private Doctor dr;
    
    public DoctorWorkAreaJPanel(Ecosystem e, User u) {
        this.ecosystem = e;
        this.dr = (Doctor) u;
        initComponents();
        jpanelHistory.setVisible(false);
        populateHistory();
        
  
        
    }
    private void populateHistory(){
        
        RequestDirectory reqDir = ecosystem.getRequestDirectory();
        DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
        
        ArrayList<Request> drReq = reqDir.getRequestByDrId(dr.getId());
        
        for(Request r: drReq){
            model.addRow(new Object[]{r.getId(), r.getBloodType(),r.getUnit(), r.getStatus()});
        }        
                
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRaiseReq = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcomboBlood = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jcomboQty = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jpanelHistory = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCmpl = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1200, 600));

        jLabel1.setFont(new java.awt.Font("Oriya Sangam MN", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Welcome to Brigham Hospital");

        btnRaiseReq.setBackground(new java.awt.Color(204, 0, 0));
        btnRaiseReq.setForeground(new java.awt.Color(255, 255, 255));
        btnRaiseReq.setText("Raise Request");
        btnRaiseReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseReqActionPerformed(evt);
            }
        });

        btnHistory.setBackground(new java.awt.Color(204, 0, 0));
        btnHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnHistory.setText("Request History");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Oriya Sangam MN", 1, 14)); // NOI18N
        jLabel2.setText("Select Blood Type from below list to make a request");

        jLabel3.setFont(new java.awt.Font("Oriya Sangam MN", 1, 14)); // NOI18N
        jLabel3.setText("Select Blood Type");

        jcomboBlood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "AB+", "AB-", "O+", "O-", "B+", "B-" }));
        jcomboBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboBloodActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Oriya Sangam MN", 1, 14)); // NOI18N
        jLabel4.setText("Select Quantity");

        jcomboQty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jcomboQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboQtyActionPerformed(evt);
            }
        });

        jLabel6.setText("Units");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/images/doctor.jpeg"))); // NOI18N

        tblHistory.setBackground(new java.awt.Color(153, 204, 255));
        tblHistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Type of blood", "Units", "Request Status"
            }
        ));
        jScrollPane2.setViewportView(tblHistory);

        jLabel5.setFont(new java.awt.Font("Oriya Sangam MN", 1, 14)); // NOI18N
        jLabel5.setText("You are logged in as : Doctor");

        jpanelHistory.setBackground(new java.awt.Color(255, 255, 255));

        tblCmpl.setBackground(new java.awt.Color(153, 204, 255));
        tblCmpl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblCmpl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Type of blood", "Units", "Request Status"
            }
        ));
        jScrollPane3.setViewportView(tblCmpl);

        javax.swing.GroupLayout jpanelHistoryLayout = new javax.swing.GroupLayout(jpanelHistory);
        jpanelHistory.setLayout(jpanelHistoryLayout);
        jpanelHistoryLayout.setHorizontalGroup(
            jpanelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
            .addGroup(jpanelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelHistoryLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        jpanelHistoryLayout.setVerticalGroup(
            jpanelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
            .addGroup(jpanelHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpanelHistoryLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(jLabel5)
                                .addGap(240, 240, 240))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(btnHistory))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcomboBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jcomboQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addComponent(btnRaiseReq)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jpanelHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHistory, btnRaiseReq});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jcomboBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jcomboQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(btnRaiseReq)
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistory)
                        .addGap(8, 8, 8)
                        .addComponent(jpanelHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7)
                        .addContainerGap(38, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHistory, btnRaiseReq});

    }// </editor-fold>//GEN-END:initComponents

    private void btnRaiseReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseReqActionPerformed
        // TODO add your handling code here:
        
        Request r = new Request();
        r.setDoctorId(dr.getId());
        r.sethId(dr.gethId());
        r.setBloodType(jcomboBlood.getSelectedItem().toString());
        r.setUnit(Integer.parseInt(jcomboQty.getSelectedItem().toString()));
        ecosystem.getRequestDirectory().addRequest(r);
        
        DefaultTableModel model = (DefaultTableModel) tblHistory.getModel();
        model.addRow(new Object[]{r.getId(), r.getBloodType(),r.getUnit(), r.getStatus()});
        

        
    }//GEN-LAST:event_btnRaiseReqActionPerformed

    private void jcomboBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboBloodActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcomboBloodActionPerformed

    private void jcomboQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboQtyActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        jpanelHistory.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tblCmpl.getModel();
        
        ArrayList<Request> cmpReq = ecosystem.getRequestDirectory().getCompleted();
        
        for(Request r: cmpReq){
            model.addRow(new Object[]{r.getId(), r.getBloodType(),r.getUnit(), r.getStatus()});
        }
        
    }//GEN-LAST:event_btnHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnRaiseReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> jcomboBlood;
    private javax.swing.JComboBox<String> jcomboQty;
    private javax.swing.JPanel jpanelHistory;
    private javax.swing.JTable tblCmpl;
    private javax.swing.JTable tblHistory;
    // End of variables declaration//GEN-END:variables

    
}
